### ISSUE TITLE
Unique minis cannot be placed if already on board

### ISSUE THREAD

**Issue by pyrestriker** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#715]
**Describe the bug**
The behavior used to be that if you gabbed a Mini from the Unique Creatures menu, then you could place that mini into a new spot. This was useful if you happened to lose where the mini was on a board. Now, the action just cancels out when you try to place it.

**To Reproduce**
1. Make a unique creature
2. Place it on the board.
3. Grab the mini from the Unique Creatures menu
4. Try to place it on the board in a new location.

**Screenshots/Videos/Twitch Clips**

https://youtu.be/KotbCRKhjV8

**Comment by cbaggers** [comment]
Thanks for the report @pyrestriker, I'll see what happened there

**Comment by zorum24** [comment]
I am also seeing this issue.

Killing the unique creature and trying to place it again throws up an error. 
![20210413170822_1](https://user-images.githubusercontent.com/44488349/114632048-0a246580-9c7b-11eb-8be6-ac31649ed079.jpg)
![20210413170824_1](https://user-images.githubusercontent.com/44488349/114632049-0abcfc00-9c7b-11eb-8c18-387ee0667299.jpg)

Backing out to the main menu and loading the board again allows the mini to be placed but still cannot be placed again after the first placement.

**Comment by LuPro** [comment]
This should be fixed in the latest update, can you confirm?

**Comment by pyrestriker** [comment]
Half-fixed. Unique minis still can't be placed after you kill them. https://youtu.be/LAtO2qfu27Y
