### ISSUE TITLE
LOS Issue - Glow remains when enemy is hidden

### ISSUE THREAD

**Issue by Jangalang** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#774]
When you place something like an evil spirit on the board and move your character around a wall, the ambient glow of the character remains, giving away it's position.
![image_2021-04-16_010617](https://user-images.githubusercontent.com/30613050/114978878-8bccec80-9e4f-11eb-8d02-4be495f4021c.png)

**Comment by cbaggers** [comment]
This should be fixed in the latest build. If you have the time would you mind checking to see if it works correctly for you?

**Comment by Jangalang** [comment]
Looks like it’s still going. This is me switching from GM mode to player mode, if that helps. I also build a new board just to be sure. Still the same issue.    From: BaggersSent: Wednesday, April 21, 2021 7:57 PMTo: Bouncyrock/TaleSpire-Beta-Public-Issue-TrackerCc: Jangalang; AuthorSubject: Re: [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker] LOS Issue - Glow remains when enemy is hidden (#774) This should be fixed in the latest build. If you have the time would you mind checking to see if it works correctly for you?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
